### ISSUE TITLE
⚠️ Commit contains editorial and non-editorial changes

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#1]
[c7e06bb](https://github.com/kingrpaul/johnston-mcculley_the-mark-of-zorro/commit/c7e06bb22324457ac83ca3efdde3efa6eba38132) contains editorial and non-editorial changes that should be kept separate.

It is necessary to rebase and split that commit. It shouldn’t be too difficult but it may be challenging if you have never done it before. I recommend you tackle this before any other issues. Do not hesitate to ask if you need help.

**Comment by kingrpaul** [comment]
@Gragt I do see the problem, though I am not sure how it happened. I have never rebased or split a commit before, so help would be much appreciated. Thank you, in advance.

**Comment by Gragt** [comment]
Sure. This one should actually be fairly straigthforward.

As a precaution, you always want to do a backup of some kind. The good news is that you already have your repository pushed to GitHub, so if things go south you can just redownload everything from there. You could also create a new branch just in case, or even copy your repository (some SE contributors always recommend to do that). I’m usually happy with having my files on GitHub, but you if you feel safer taking extra steps, go ahead—better be safe than sorry.

This might be easier to do if you use a graphical interface, but it is perfectly doable from the terminal. I’ll assume we are using the latter.

We’re going to start an interactive rebase by targetting the commit we want to split:

`git rebase -i c7e06bb~`

This should open the [text editor you have associated](https://docs.github.com/en/get-started/getting-started-with-git/associating-text-editors-with-git) with Git, listing all commits until the “Add titles” one, our target. Change “pick” in front of it to “edit”, to let Git know we want to edit it. Save and close.

Once you go back to the terminal, you’ll see that the rebase has started. We are back in time right after you committed files to “Add titles.” We want to undo the commit but keep the changes so we can split them:

`git reset HEAD~`

The files are now unstaged but still modified—which is good, because we do not want to do the same work twice! All we need to do now is to select only the parts that we want to commit:

`git add -p`

This will start an interactive mode asking you whether you want to select a modified hunk for staging or not. Basically, you decide what commit you want first and only select (y) those that you want there; if something should be in another commit, reject it (n).

Once you are done, you can create a commit as usual:

`git commit -m "Name of commit"`

Then repeat the last two commands as many times as needed. You can create more than two commits. In fact, it might even be a good idea to separate editorial changes into their own commits, e.g., “some one -> someone” in one commit, “every one -> everyone” in another commit, etc.

Once all changes have been committed, it is time to apply the rest of the history on top of it:

`git rebase --continue`

As long as you didn’t introduce new changes, there shouldn’t be any conflicts and the rebase should complete successfully.

We changed the history, which means that you local branch and the one on GitHub have diverged. Once you are sure that your local repo is the way you want it, you can force the change online with:

`git push --force`

And Bob’s your uncle!

**Comment by kingrpaul** [comment]
That seems to have worked. Thank you for the walk-through. 
05682e6f79f6132927fd886f4438fddb79d84bdf
