### ISSUE TITLE
Editorial commits not labelled as such

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#2]
There are three commits dedicated to modernise spelling, .i.e., editorial commits. They should be prefixed with the [Editorial] tag. Additionaly, [e2e1fa2](https://github.com/kingrpaul/johnston-mcculley_the-mark-of-zorro/commit/e2e1fa20beca17566776511e7fd7778dbde24eb2) mentions this fact in its title; it should be removed so the title only state what the commit does.

**Comment by kingrpaul** [comment]
77df227f00abe0566ee051959f4fbc7a629c4bbe
