### ISSUE TITLE
Unnecessary change

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#3]
[f8232cb](https://github.com/kingrpaul/johnston-mcculley_the-mark-of-zorro/commit/f8232cb66d0f3a5fdae72db701ccf0a26db2b70e) changes instances of Carlos’s to Carlos’. This change is unnecessary and should be reverted.

“Carlos’s” is the correct possessive case according to the Chicago Manuel of Style—which we are supposed to fall back on if something isn’t covered in the SEMOS.

**Comment by kingrpaul** [comment]
c870cb4b2c7f347ed583fc3ed681b80012665788
