### ISSUE TITLE
Colophon: painting date is represented as a fraction.

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#4]
In the colophon, the date for the painting used as cover is currently rendered as ¹⁸⁴⁸⁄₁₈₅₄—this change was made by typogryphy.

The line `a painting completed in ¹⁸⁴⁸⁄₁₈₅₄ by` should probably be rewritten as `a painting completed between 1848 and 1854 by`.

**Comment by kingrpaul** [comment]
364f6f48b7ddbeb81719f57fa59df63ceacb5753
