### ISSUE TITLE
content.opf: Miscellaneous metadata issues

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#5]
There are a couple metadata issues in `content.opf`:
* `<meta property="se:url.encyclopedia.wikipedia">` should redirect to [https://en.wikipedia.org/wiki/The_Curse_of_Capistrano](https://en.wikipedia.org/wiki/The_Curse_of_Capistrano).
* `<meta property="se:name.person.full-name" refines="#author">` should be removed since it wasn’t changed.

**Comment by kingrpaul** [comment]
c3f4429682e4b690c9d51b0d91f2552c960390bc
