### ISSUE TITLE
[Suggestions] Short and long descriptions tweaks

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#6]
Could it be possible to shorten the short description? It appears to be on the long side.

Semicolons in the first part of long description seem wrong.

Consider adding the following information to the long description:
* The original title of the story, as it was serialised, was *The Curse of Capistrano*.
* [Irish adventurer William Lamport](https://www.irishtimes.com/life-and-style/abroad/the-mark-of-lamport-the-real-zorro-was-from-wexford-1.3059440) may have inspired the character of Zorro.

**Comment by kingrpaul** [comment]
Shortened the short description and expanded the long description. 
`se clean` would not accept _The Curse of Capistrano_ marked as a novel. So, it is italicized only. Not sure this has come up before (for me) and may be because it's in the content file? Any thoughts?

**Comment by Gragt** [comment]
You do not need to semanticate anything in the short/long description. That’s because they are part of the book’s metadata but not part of the book itself. It is fine to stick to italics there.

**Comment by kingrpaul** [comment]
Nice. Then, I think that's it. Let me know if there's anything else. And, thank you for the review.
