### ISSUE TITLE
[Suggestion] Semanticate some Spanish words

### ISSUE THREAD

**Issue by Gragt** [kingrpaul/johnston-mcculley_the-mark-of-zorro#7]
There are a few unsemanticated Spanish words. It is visually fine, but the idea of explicitely identifying the language is to make it easy for accessibilty software to read them correctly.

Words like señor or caballero should be common enough (I think), but I wonder about the names of places like Reina de Los Angeles.

**Comment by kingrpaul** [comment]
@Gragt I want to double-check this one. It’s my understanding that we only a semanticate a word with language when it is italicized as foreign and that words in Merriam-Webster are treated as English except in cases where Merriam-Webster says they are foreign. Merriam-Webster includes many word I wouldn’t think of as being English, such as ‘caballero’ and ‘señor’ but I have been treating all these words as English if I find them there. Does that seem that right?

SEMOS says generally not to italicize proper nouns, but to semanticate in a <span> if they’re likely mispronounced, which I don’t think is the case here. Los Angeles is, of course still a place, and googling ‘Reina’ produces a good number of addresses across the U.S. Fair enough?

**Comment by Gragt** [comment]
Yes, that’s correct. I don’t think these should be italicised; mostly I wondered if these shouldn’t be flagged as Spanish so they would be pronounced correctly. I imagined that you had already thought of it while working on the book, so I just wanted to check that with you.

If you feel this won’t an issue, feel free to ignore this.

**Comment by kingrpaul** [comment]
Appreciate the feedback and do think it's correct.
